version: 2.1
orbs:
  node: circleci/node@1.1.6
  browser-tools: circleci/browser-tools@x.y
jobs:
  build-and-test:
    docker:
      - image: 'cimg/node:13.12'
    executor:
      name: node/default
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test ngx-chess-board
workflows:
    build-and-test:
      jobs:
        - build-and-test
