version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
      environment:
        CHROME_BIN: /usr/bin/google-chrome

    steps:
      - checkout
      - run: npm install
      - run: npm test ngx-chess-board
