import { EventEmitter } from '@angular/core';
import { PiecePromotionModalComponent } from '../piece-promotion/piece-promotion-modal/piece-promotion-modal.component';
import { HistoryMove } from '../history-move-provider/history-move';
import { ColorInput, PieceTypeInput } from '../utils/inputs/piece-type-input';
import { BoardLoader } from './board-state-provider/board-loader';
import { BoardStateProvider } from './board-state-provider/board-state-provider';
import { MoveStateProvider } from './board-state-provider/move-state-provider';
import { CoordsProvider } from './coords/coords-provider';
import { ColorStrategy } from './drawing-tools/colors/color-strategy';
import { DrawPoint } from './drawing-tools/draw-point';
import { DrawProvider } from './drawing-tools/draw-provider';
import { HistoryMoveProvider } from '../history-move-provider/history-move-provider';
import { Board } from '../models/board';
import { Color } from '../models/pieces/color';
import { Piece } from '../models/pieces/piece';
import { Point } from '../models/pieces/point';
import { PieceIconInputManager } from '../utils/inputs/piece-icon-input-manager';
import { DragEndStrategy } from './drag/end/drag-end-strategy';
import { DragStartStrategy } from './drag/start/drag-start-strategy';
import { MoveChange } from './move-change';
export declare class EngineFacade {
    _board: Board;
    _selected: boolean;
    _freeMode: boolean;
    drawPoint: DrawPoint;
    drawProvider: DrawProvider;
    disabling: boolean;
    dragDisabled: boolean;
    drawDisabled: boolean;
    boardStateProvider: BoardStateProvider;
    moveStateProvider: MoveStateProvider;
    moveHistoryProvider: HistoryMoveProvider;
    heightAndWidth: number;
    lightDisabled: boolean;
    darkDisabled: boolean;
    moveChange: EventEmitter<MoveChange>;
    boardLoader: BoardLoader;
    coords: CoordsProvider;
    pieceIconManager: PieceIconInputManager;
    dragStartStrategy: DragStartStrategy;
    dragEndStrategy: DragEndStrategy;
    colorStrategy: ColorStrategy;
    modal: PiecePromotionModalComponent;
    constructor(board: Board, moveChange: EventEmitter<MoveChange>);
    reset(): void;
    undo(): void;
    getMoveHistory(): HistoryMove[];
    saveMoveClone(): void;
    move(coords: string): void;
    prepareActivePiece(pieceClicked: Piece, pointClicked: Point): void;
    onPieceClicked(pieceClicked: any, pointClicked: any): void;
    handleClickEvent(pointClicked: Point, isMouseDown: boolean): void;
    onMouseDown(event: MouseEvent, pointClicked: Point, left?: number, top?: number): void;
    onMouseUp(event: MouseEvent, pointClicked: Point, left: number, top: number): void;
    saveClone(): void;
    movePiece(toMovePiece: Piece, newPoint: Point, promotionIndex?: number): void;
    checkForPawnPromote(toPromotePiece: Piece, promotionIndex?: number): boolean;
    checkIfPawnFirstMove(piece: Piece): void;
    checkIfRookMoved(piece: Piece): void;
    checkIfKingMoved(piece: Piece): void;
    afterMoveActions(promotionIndex?: number): void;
    checkForPat(color: Color): boolean;
    openPromoteDialog(piece: Piece): void;
    checkForPossibleMoves(color: Color): boolean;
    disableSelection(): void;
    /**
     * Processes logic to allow freeMode based logic processing
     */
    onFreeMode(pieceClicked: any): void;
    isPieceDisabled(pieceClicked: Piece): boolean;
    addDrawPoint(x: number, y: number, crtl: boolean, alt: boolean, shift: boolean, left: number, top: number): void;
    increaseFullMoveCount(): void;
    get board(): Board;
    set board(value: Board);
    get selected(): boolean;
    set selected(value: boolean);
    get freeMode(): boolean;
    set freeMode(value: boolean);
    addPiece(pieceTypeInput: PieceTypeInput, colorInput: ColorInput, coords: string): void;
}
